UPDATE part_templates
SET category = CASE LOWER(TRIM(category))
    WHEN 'body' THEN 'body'
    WHEN 'кузов' THEN 'body'
    WHEN 'optics' THEN 'optics'
    WHEN 'оптика' THEN 'optics'
    WHEN 'engine' THEN 'engine'
    WHEN 'двигун' THEN 'engine'
    WHEN 'transmission' THEN 'transmission'
    WHEN 'кпп / трансмісія' THEN 'transmission'
    WHEN 'трансмісія' THEN 'transmission'
    WHEN 'suspension' THEN 'suspension'
    WHEN 'ходова' THEN 'suspension'
    WHEN 'підвіска' THEN 'suspension'
    WHEN 'brakes' THEN 'brakes'
    WHEN 'гальма' THEN 'brakes'
    WHEN 'electric' THEN 'electric'
    WHEN 'electrical' THEN 'electric'
    WHEN 'електрика' THEN 'electric'
    WHEN 'interior' THEN 'interior'
    WHEN 'салон' THEN 'interior'
    WHEN 'cooling / ac' THEN 'cooling'
    WHEN 'cooling' THEN 'cooling'
    WHEN 'охолодження / кондиціонер' THEN 'cooling'
    WHEN 'охолодження' THEN 'cooling'
    WHEN 'mirrors / glass' THEN 'glass'
    WHEN 'glass' THEN 'glass'
    WHEN 'дзеркала / скло' THEN 'glass'
    WHEN 'інше' THEN 'other'
    WHEN 'other' THEN 'other'
    ELSE 'other'
END;

UPDATE seller_parts
SET category = CASE LOWER(TRIM(category))
    WHEN 'body' THEN 'body'
    WHEN 'кузов' THEN 'body'
    WHEN 'optics' THEN 'optics'
    WHEN 'оптика' THEN 'optics'
    WHEN 'engine' THEN 'engine'
    WHEN 'двигун' THEN 'engine'
    WHEN 'transmission' THEN 'transmission'
    WHEN 'кпп / трансмісія' THEN 'transmission'
    WHEN 'трансмісія' THEN 'transmission'
    WHEN 'suspension' THEN 'suspension'
    WHEN 'ходова' THEN 'suspension'
    WHEN 'підвіска' THEN 'suspension'
    WHEN 'brakes' THEN 'brakes'
    WHEN 'гальма' THEN 'brakes'
    WHEN 'electric' THEN 'electric'
    WHEN 'electrical' THEN 'electric'
    WHEN 'електрика' THEN 'electric'
    WHEN 'interior' THEN 'interior'
    WHEN 'салон' THEN 'interior'
    WHEN 'cooling / ac' THEN 'cooling'
    WHEN 'cooling' THEN 'cooling'
    WHEN 'охолодження / кондиціонер' THEN 'cooling'
    WHEN 'охолодження' THEN 'cooling'
    WHEN 'mirrors / glass' THEN 'glass'
    WHEN 'glass' THEN 'glass'
    WHEN 'дзеркала / скло' THEN 'glass'
    WHEN 'інше' THEN 'other'
    WHEN 'other' THEN 'other'
    ELSE 'other'
END,
updated_at = NOW();
